import Foundation

/// 화면 문구 키 (T-363) — 웰컴·정보·팔레트.
extension L10n {
    enum Welcome {
        static let docLink = L10nKey("welcome.link.docs")
        static let docLinkDetail = L10nKey("welcome.link.docsDetail")
        static let github = L10nKey("welcome.link.github")
        static let githubDetail = L10nKey("welcome.link.githubDetail")
        static let appRepo = L10nKey("welcome.link.appRepo")
        static let appRepoDetail = L10nKey("welcome.link.appRepoDetail")
        static let huggingFace = L10nKey("welcome.link.huggingFace")
        static let huggingFaceDetail = L10nKey("welcome.link.huggingFaceDetail")
        static let gallery = L10nKey("welcome.link.gallery")
        static let galleryDetail = L10nKey("welcome.link.galleryDetail")
        static let upgradeTitle = L10nKey("welcome.upgrade.title")
        static let runUpgrade = L10nKey("welcome.upgrade.run")
        static let cancel = L10nKey("welcome.cancel")
        static let upgradeNote = L10nKey("welcome.upgrade.note")
        static let tagline = L10nKey("welcome.tagline")
        static let checking = L10nKey("welcome.checking")
        static let latest = L10nKey("welcome.latest")
        static let updateAvailable = L10nKey("welcome.updateAvailable")
        static let releaseNotes = L10nKey("welcome.notes.title")
        static let offlineSaved = L10nKey("welcome.notes.offline")
        static let refreshNotes = L10nKey("welcome.notes.refresh")
        static let notesFailed = L10nKey("welcome.notes.failed")
        static let prerelease = L10nKey("welcome.notes.prerelease")
        static let readMore = L10nKey("welcome.readMore")
        static let available = L10nKey("welcome.version.available")
        static let updating = L10nKey("welcome.version.updating")
        static let update = L10nKey("welcome.version.update")
        static let recommendedLinks = L10nKey("welcome.links.title")
        static let openLink = L10nKey("welcome.links.open")
        static let source = L10nKey("welcome.links.source")
        static let startHint = L10nKey("welcome.startHint")
        static let upgradeDone = L10nKey("welcome.upgrade.done")
        static let upgradeFailed = L10nKey("welcome.upgrade.failed")
    }

    enum About {
        static let version = L10nKey("about.version")
        static let author = L10nKey("about.author")
        static let tagline = L10nKey("about.tagline")
        static let libraries = L10nKey("about.libraries")
    }
    enum Palette {
        static let newChat = L10nKey("palette.cmd.newChat")
        static let serverStop = L10nKey("palette.cmd.serverStop")
        static let serverDisconnect = L10nKey("palette.cmd.serverDisconnect")
        static let serverStart = L10nKey("palette.cmd.serverStart")
        static let refreshModels = L10nKey("palette.cmd.refreshModels")
        static let refreshModelsDetail = L10nKey("palette.cmd.refreshModelsDetail")
        static let modelManager = L10nKey("palette.cmd.modelManager")
        static let modelManagerDetail = L10nKey("palette.cmd.modelManagerDetail")
        static let logPanel = L10nKey("palette.cmd.logPanel")
        static let debugPanel = L10nKey("palette.cmd.debugPanel")
        static let newBenchmark = L10nKey("palette.cmd.newBenchmark")
        static let newBenchmarkDetail = L10nKey("palette.cmd.newBenchmarkDetail")
        static let openBenchmark = L10nKey("palette.cmd.openBenchmark")
        static let openBenchmarkDetail = L10nKey("palette.cmd.openBenchmarkDetail")
        static let searchPlaceholder = L10nKey("palette.search.placeholder")
        static let clear = L10nKey("palette.clear")
        static let sectionRecent = L10nKey("palette.section.recent")
        static let sectionCommands = L10nKey("palette.section.commands")
        static let sectionChats = L10nKey("palette.section.chats")
        static let sectionBenchmarks = L10nKey("palette.section.benchmarks")
        static let empty = L10nKey("palette.empty")
        static let busy = L10nKey("palette.busy")
        static let renameTitle = L10nKey("palette.rename.title")
        static let renameNote = L10nKey("palette.rename.note")
        static let renamePlaceholder = L10nKey("palette.rename.placeholder")
        static let cancel = L10nKey("palette.cancel")
        static let save = L10nKey("palette.save")
    }

}
