import Foundation

/// 화면 문구 키 (T-363) — 웰컴·정보·팔레트.
extension L10n {
    enum Welcome {
        static let docLink = L10nKey("welcome.link.docs")
        static let docLinkDetail = L10nKey("welcome.link.docsDetail")
        static let github = L10nKey("welcome.link.github")
        static let githubDetail = L10nKey("welcome.link.githubDetail")
        static let appRepo = L10nKey("welcome.link.appRepo")
        static let appRepoDetail = L10nKey("welcome.link.appRepoDetail")
        static let huggingFace = L10nKey("welcome.link.huggingFace")
        static let huggingFaceDetail = L10nKey("welcome.link.huggingFaceDetail")
        static let gallery = L10nKey("welcome.link.gallery")
        static let galleryDetail = L10nKey("welcome.link.galleryDetail")
        static let upgradeTitle = L10nKey("welcome.upgrade.title")
        static let runUpgrade = L10nKey("welcome.upgrade.run")
        static let cancel = L10nKey("welcome.cancel")
        static let upgradeNote = L10nKey("welcome.upgrade.note")
        static let tagline = L10nKey("welcome.tagline")
        static let checking = L10nKey("welcome.checking")
        static let latest = L10nKey("welcome.latest")
        static let updateAvailable = L10nKey("welcome.updateAvailable")
        static let releaseNotes = L10nKey("welcome.notes.title")
        static let offlineSaved = L10nKey("welcome.notes.offline")
        static let refreshNotes = L10nKey("welcome.notes.refresh")
        static let notesFailed = L10nKey("welcome.notes.failed")
        static let prerelease = L10nKey("welcome.notes.prerelease")
        static let readMore = L10nKey("welcome.readMore")
        static let available = L10nKey("welcome.version.available")
        static let updating = L10nKey("welcome.version.updating")
        static let update = L10nKey("welcome.version.update")
        static let recommendedLinks = L10nKey("welcome.links.title")
        static let openLink = L10nKey("welcome.links.open")
        static let source = L10nKey("welcome.links.source")
        static let startHint = L10nKey("welcome.startHint")
        static let upgradeDone = L10nKey("welcome.upgrade.done")
        static let upgradeFailed = L10nKey("welcome.upgrade.failed")
    }

    enum About {
        static let version = L10nKey("about.version")
        static let author = L10nKey("about.author")
        static let tagline = L10nKey("about.tagline")
        static let libraries = L10nKey("about.libraries")
    }
    enum Palette {
        static let newChat = L10nKey("palette.cmd.newChat")
        static let serverStop = L10nKey("palette.cmd.serverStop")
        static let serverDisconnect = L10nKey("palette.cmd.serverDisconnect")
        static let serverStart = L10nKey("palette.cmd.serverStart")
        static let refreshModels = L10nKey("palette.cmd.refreshModels")
        static let refreshModelsDetail = L10nKey("palette.cmd.refreshModelsDetail")
        static let modelManager = L10nKey("palette.cmd.modelManager")
        static let modelManagerDetail = L10nKey("palette.cmd.modelManagerDetail")
        static let logPanel = L10nKey("palette.cmd.logPanel")
        static let debugPanel = L10nKey("palette.cmd.debugPanel")
        static let newBenchmark = L10nKey("palette.cmd.newBenchmark")
        static let newBenchmarkDetail = L10nKey("palette.cmd.newBenchmarkDetail")
        static let openBenchmark = L10nKey("palette.cmd.openBenchmark")
        static let openBenchmarkDetail = L10nKey("palette.cmd.openBenchmarkDetail")
        static let searchPlaceholder = L10nKey("palette.search.placeholder")
        static let clear = L10nKey("palette.clear")
        static let sectionRecent = L10nKey("palette.section.recent")
        static let sectionCommands = L10nKey("palette.section.commands")
        static let sectionChats = L10nKey("palette.section.chats")
        static let sectionBenchmarks = L10nKey("palette.section.benchmarks")
        static let empty = L10nKey("palette.empty")
        static let busy = L10nKey("palette.busy")
        static let renameTitle = L10nKey("palette.rename.title")
        static let renameNote = L10nKey("palette.rename.note")
        static let renamePlaceholder = L10nKey("palette.rename.placeholder")
        static let cancel = L10nKey("palette.cancel")
        static let save = L10nKey("palette.save")
    }

    enum Catalog {
        static let searchPlaceholder = L10nKey("catalog.searchPlaceholder")
        static let toRecommended = L10nKey("catalog.toRecommended")
        static let recommendedSection = L10nKey("catalog.recommended")
        static let seeAll = L10nKey("catalog.seeAll")
        static let installed = L10nKey("catalog.installed")
        static let notInstalled = L10nKey("catalog.notInstalled")
        static let count = L10nKey("catalog.count")
        static let noResults = L10nKey("catalog.noResults")
        static let noResultsDetail = L10nKey("catalog.noResultsDetail")
        static let loading = L10nKey("catalog.loading")
        static let loadMore = L10nKey("catalog.loadMore")
        static let updatedToday = L10nKey("catalog.updatedToday")
        static let updatedDaysAgo = L10nKey("catalog.updatedDaysAgo")
        static let installedSummary = L10nKey("catalog.installedSummary")
        static let open = L10nKey("catalog.open")
        static let pickModel = L10nKey("catalog.pickModel")
        static let pickModelDetail = L10nKey("catalog.pickModelDetail")
        static let copyRepoID = L10nKey("catalog.copyRepoID")
        static let updatedTodayFull = L10nKey("catalog.updatedTodayFull")
        static let updatedDaysAgoFull = L10nKey("catalog.updatedDaysAgoFull")
        static let params = L10nKey("catalog.params")
        static let numbersNote = L10nKey("catalog.numbersNote")
        static let downloadOptions = L10nKey("catalog.downloadOptions")
        static let noLiteFile = L10nKey("catalog.noLiteFile")
        static let fileSelect = L10nKey("catalog.fileSelect")
        static let localModelID = L10nKey("catalog.localModelID")
        static let download = L10nKey("catalog.download")
        static let hfToken = L10nKey("catalog.hfToken")
        static let hfTokenHelp = L10nKey("catalog.hfTokenHelp")
        static let manualDownload = L10nKey("catalog.manualDownload")
        static let manualDownloadHelp = L10nKey("catalog.manualDownloadHelp")
        static let permissionOff = L10nKey("catalog.permissionOff")
        static let duplicateDownload = L10nKey("catalog.duplicateDownload")
        static let downloadRequested = L10nKey("catalog.downloadRequested")
        static let downloadFailed = L10nKey("catalog.downloadFailed")
        static let unknownCause = L10nKey("catalog.unknownCause")
        static let supportNote = L10nKey("catalog.supportNote")
        static let modelDescription = L10nKey("catalog.modelDescription")
        static let noDescription = L10nKey("catalog.noDescription")
    }

    enum Import {
        static let title = L10nKey("import.title")
        static let fetchNew = L10nKey("import.fetchNew")
        static let close = L10nKey("import.close")
        static let startDownload = L10nKey("import.startDownload")
        static let stepModel = L10nKey("import.stepModel")
        static let stepFile = L10nKey("import.stepFile")
        static let stepSave = L10nKey("import.stepSave")
        static let stepProgress = L10nKey("import.stepProgress")
        static let recommended = L10nKey("import.recommended")
        static let manualEntry = L10nKey("import.manualEntry")
        static let repoPlaceholder = L10nKey("import.repoPlaceholder")
        static let repoPage = L10nKey("import.repoPage")
        static let checkFileHelp = L10nKey("import.checkFileHelp")
        static let pickFile = L10nKey("import.pickFile")
        static let filePlaceholder = L10nKey("import.filePlaceholder")
        static let localIDPlaceholder = L10nKey("import.localIDPlaceholder")
        static let tokenPlaceholder = L10nKey("import.tokenPlaceholder")
        static let duplicate = L10nKey("import.duplicate")
        static let pending = L10nKey("import.pending")
        static let badRepo = L10nKey("import.badRepo")
        static let noLiteFile = L10nKey("import.noLiteFile")
        static let fetchFailed = L10nKey("import.fetchFailed")
    }
}
